openapi: 3.0.3
info:
  title: SearchProcessLayer
  description: Process Layer from which each query starts
  version: 1.0.0
servers:
  - url: https://search-pl/api/v1
paths:
  /:
    get:
      summary: Search sitting spots
      description: Generate a query with the specified parameter and return a list of sitting spots
      operationId: searchSittingSpot
      parameters:
        - name: location
          in: query
          description: General position of the search
          required: true
          schema:
            $ref: '#/components/schemas/Area'
        - name: tags
          in: query
          description: Tags of the sitting spot
          required: false
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Tag'
        - name: labels
          in: query
          description: Labels of the sitting spot
          required: false
          schema:
            type: array
            items:
              type: string
      responses:
        200:
          description: Operation succesful
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/QueryResult'
components:
  schemas:
    Location:
      description: x,y coordinates
      properties:
        x:
          type: number
        y:
          type: number
    Area:
      description: An area with a location as center
      properties:
        center:
          $ref: '#/components/schemas/Location'
        range:
          type: number
    Tag:
      properties:
        key:
          type: string
        value:
          type: string
    QueryResult:
      properties:
        spotId:
          type: string
          format: uuid
        location:
          $ref: '#/components/schemas/Location'
